apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quarkus-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-sample
    app.kubernetes.io/part-of: test
  name: quarkus-sample
  namespace: mdsaud
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: quarkus-sample
    weight: 100
status: {}
